$sql_create_table ="CREATE TABLE CpnMember4(
	    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    	name VARCHAR(50) NOT NULL,
    	familyName VARCHAR(50) NOT NULL,
		upfile VARCHAR(300) NOT NULL,
    	telephone VARCHAR(50) NULL, 
    	mobileNumber VARCHAR(30) NOT NULL,
    	email VARCHAR(50) NULL,
    	dateOfBirth VARCHAR(50) NOT NULL,
    	motherName VARCHAR(50) NOT NULL,
    	fatherName VARCHAR(50) NOT NULL,
    	maritalStatus VARCHAR(15) NOT NULL, 
    	spouceName VARCHAR(50)  NULL,
    	permanentAddress VARCHAR(100) NOT NULL, 
    	temporaryAddress VARCHAR(100)  NULL,
 		education VARCHAR(50) NOT NULL,
 		profession VARCHAR(50) NOT NULL,
 		firstMembershipDate VARCHAR(50) NOT NULL, 
 		lastMembershipDate VARCHAR(50) NOT NULL, 
 		validUntil VARCHAR(50) NOT NULL, 
 		district VARCHAR(50) NOT NULL,
    	region VARCHAR(50) NOT NULL,
    	workingCommitte VARCHAR(50) NOT NULL, 
    	politicalBackground VARCHAR(2000) NOT NULL,
    	partyResponsibilities VARCHAR(2000) NOT NULL,
    	politicalAppointments VARCHAR(2000)  NULL,
    	suggestions VARCHAR(1000) NOT NULL,
    	acceptance BOOL NOT NULL, 
		memberVerified BOOL NULL,
		verificationDate DATE NULL,
    	english_dob DATE  NULL, 
        english_first_mebmer_date DATE NULL,
        english_last_mebmer_date DATE NULL,
        english_last_valid_until DATE NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    	);"; 
    	